spring:
  application:
    name: detail-storage
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/detail_storage_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Ayrat14Bigboss14}
  jpa:
    generate-ddl: true
    show-sql: true
    properties.hibernate.format_sql: true

server:
  port: 8080


